Update main.go
I was getting following error 
```
    ./main.go:47:4: cannot use pulumi.Map literal (type pulumi.Map) as type pulumi.StringMapInput in field value:
    	pulumi.Map does not implement pulumi.StringMapInput (missing ToStringMapOutput method)
```
when used `pulumi.Map` in Tags in ec2.NewInstance.
versions:
```
	github.com/pulumi/pulumi-aws/sdk/v3 v3.31.0
	github.com/pulumi/pulumi/sdk/v2 v2.22.0
```